[package]
name = "guessing_game"
version = "0.1.0"
authors = ["George Hipp <george.hipp.jr@gmail.com>"]

[dependencies]

rand = "0.4.0"
assert_cli = "0.5"

[[bin]]
name = "main"
path = "src/bin/main.rs"